application: solar-compare
version: 2
runtime: go
api_version: go1

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
    
- url: /html
  static_dir: html
  
- url: /css
  static_dir: html/css
  
- url: /scripts
  static_dir: html/scripts

- url: /.*
  script: _go_app
